/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,js,jsx}'],
  theme: {
    colors: {
      white: '#FFFFFF',
      'primary-black': '#191919',
      'primary-grey': '#7B7B7B',
      'secondary-grey': '#E3E3E3',
      'tertiary-grey': '#F6F6F6',
      'primary-blue': '#25C0F2',
      'secondary-blue': '#E6F6FA',
      'primary-purple': '#DB50FF',
      'secondary-purple': '#FEE6FE',
      'primary-green': '#00D795',
      'secondary-green': '#E6FAF3',
      'primary-red': '#FE2F40',
      'secondary-red': '#FCEEEF',
      'primary-yellow': '#FECA12',
      'secondary-yellow': '#FEF7E6',
      'primary-orange': '#FFA500',
      'secondary-orange': '#FFF2D9',
      'primary-pink': '#FF69B4',
      'secondary-pink': '#FFE6F1',
      'primary-lime': '#32CD32',
      'secondary-lime': '#E3F8E4',
      'primary-indigo': '#4B0082',
      'secondary-indigo': '#D0C9E8',
      'primary-coral': '#FF7F50',
      'secondary-coral': '#FFE3D1',
      'primary-cinder': '#14161e',
      'secondary-cinder': '#748297',
      'primary-ember': '#ff5924',
      'primary-teal': '#65918B',
      'secondary-teal': '#BDE3DE',
      'primary-tan': '#8E8A74',
      'secondary-tan': '#E7E1D2',
      'tertiary-tan': '#FAF8ED',
    },
    extend: {
      fontFamily: {
        primary: ['Inter', 'sans-serif'],
        secondary: ['Mukta', 'sans-serif'],
        tertiary: ['"Nanum Myeongjo"', 'serif'],
      },
    },
  },
  plugins: [],
};
